dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

scala:
  - 2.12.9
  
install: mvn validate -Pinstall-dependencies

script: mvn clean compile
