package conexp.fx.core.dl;

public enum Constructor {
  CONJUNCTION,
  EXISTENTIAL_RESTRICTION,
  VALUE_RESTRICTION,
  QUALIFIED_AT_LEAST_RESTRICTION,
  QUALIFIED_AT_MOST_RESTRICTION,
  PRIMITIVE_NEGATION,
  EXISTENTIAL_SELF_RESTRICTION,
  SIMPLE_ROLE_INCLUSION,
  COMPLEX_ROLE_INCLUSION;
}
